### ISSUE TITLE
Herramientas a usar

### ISSUE THREAD

**Issue by ManuelJNunez** [tdd-IgnasiYManu/MovieBot#6]
Necesitamos elegir las herramientas que usaremos para desarrollar nuestro proyecto.

**Comment by ManuelJNunez** [comment]
Creo que nos vendría mejor usar Python con la biblioteca [Pyrogram](https://docs.pyrogram.org/), ya que tiene mejor documentación que todas las demás bibliotecsa para construir bots de telegram. Además necesitariamos Flask para hacer llamadas a la API de la base de datos de películas.

**Comment by IgnasiCR** [comment]
Me parece bien, la verdad. Pyrogram es una biblioteca más completa y actualizada para construir el bot que queremos en el proyecto. Además creo que sería una buena idea utilizar Logstash para el sistema de logging por ser software libre y recomendado por el profesor.

**Comment by ManuelJNunez** [comment]
> Me parece bien, la verdad. Pyrogram es una biblioteca más completa y actualizada para construir el bot que queremos en el proyecto. Además creo que sería una buena idea utilizar Logstash para el sistema de logging por ser software libre y recomendado por el profesor.

Me parece bien, además es gratuito. Además de todas las herramientas que hemos puesto hasta ahora nos vendría bien usar un software para configuración remota como etcd, por comodidad.

**Comment by IgnasiCR** [comment]
¡De acuerdo! Además, estaría bien utilizar Google Cloud para montar todo el proyecto.

**Comment by ManuelJNunez** [comment]
Flask no lo vamos a usar, ya que sirve para crear APIs REST, lo que sí usaremos será la biblioteca `requests`, además necesitamos usar una BD para guardar las películas que el usuario tiene añadidas a "Ver más tarde". Creo que podriamos usar postgresql.

**Comment by IgnasiCR** [comment]
¡Me parece correcto! Quitamos entonces Flask, y añadimos lo que has comentado. El proyecto va en buen camino así.

**Comment by ManuelJNunez** [comment]
Hola, reabro porque quería añadir que tal vez sería mejor usar Heroku para el despliegue, ya que es gratuito para siempre y podremos tener el bot desplegado todo el tiempo que queramos sin gastar dinero.

**Comment by IgnasiCR** [comment]
Tal como te comenté una vez, es verdad que Heroku podría ser una buena opción aunque al final nos decantamos por Google Cloud. Aún estamos a tiempo de cambiar, así que por mi lo veo bien.
